# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run PDK unit tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Run pdk validate with Puppet 8
      uses: puppets-epic-show-theatre/action-pdk-validate@v1
      with:
        puppet-version: "8"
        pe-version: ""

    - name: Run pdk validate with Puppet 7
      uses: puppets-epic-show-theatre/action-pdk-validate@v1
      with:
        puppet-version: "7"
        pe-version: ""

    - name: Run unit tests with Puppet 8
      uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
      with:
        puppet-version: "8"
        pe-version: ""

    - name: Run unit tests with Puppet 7
      uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
      with:
        puppet-version: "7"
        pe-version: ""
